[package]
name = "repulsion"
version = "0.1.0"
edition = "2021"

# [profile.dev]
# overflow-checks = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
image = "0.23.14"
